// Generated by ktstore. Expectations must be supplied by the application.
package example.generated

import com.latenighthack.ktstore.*

suspend fun verifyGeneratedStoreMigrations(
    backend: (DatabaseConfiguration) -> LifecycleStoreDelegate,
    identity: String,
) {
    MigrationVerifier(example.UsersHistory.catalog, example.UsersHistory.fixtures)
        .verify(backend, identity, generatedStoreMigrations)
}
