package com.latenighthack.ktstore.tooling

import com.latenighthack.ktstore.*
import kotlinx.coroutines.runBlocking
import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

/** Deterministic generation from a compiled specification, never from source parsing. */
object MigrationTool {
    private val identifier = Regex("[A-Za-z_][A-Za-z0-9_]*")
    private val keywords = setOf("as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null", "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var", "when", "while")
    private fun reference(value: String): String {
        require(value.contains('.') && value.split('.').all { identifier.matches(it) }) { "A qualified Kotlin reference is required" }
        return value.split('.').joinToString(".") { if (it in keywords) "`$it`" else it }
    }
    fun generate(specification: MigrationSpecification, packageName: String, specificationReference: String): Map<String, String> {
        MigrationVerifier(specification.catalog, specification.fixtures).validateFixtures()
        val pkg = reference(packageName)
        val spec = reference(specificationReference)
        val catalog = specification.catalog
        val code = buildString {
            append("// Generated by ktstore. Edit the migration specification, then regenerate.\npackage $pkg\n\nimport com.latenighthack.ktstore.*\n\n")
            append("val generatedStoreMigrations: List<DatabaseMigration> = listOf(\n")
            catalog.transitions.forEach { transition ->
                val source = reference(transition.source.reference)
                val target = reference(transition.target.reference)
                append("    DatabaseMigration.configured(${transition.source.version}, ${transition.target.version}, $source.declarations, $target.declarations) {\n")
                transition.entries.forEach { entry ->
                    val ref = reference(entry.reference)
                    when (entry) {
                        is MappedStoreMigration<*, *> -> {
                            val operation = if (entry.source.declaration.signatureForTooling() == entry.target.declaration.signatureForTooling() && entry.source.indexEncodings == entry.target.indexEncodings) "transformMappedStore" else "rebuildMappedStore"
                            append("        $operation($ref.source, $ref.target, $ref.mapping)\n")
                        }
                        is CreateStoreMigration -> append("        createStore($ref.target.declaration)\n")
                        is RemoveStoreMigration -> append("        removeStore($ref.source.storeName)\n")
                    }
                }
                append("    },\n")
            }
            append(")\n")
        }
        val verification = """
            // Generated by ktstore. Expectations must be supplied by the application.
            package $pkg

            import com.latenighthack.ktstore.*

            suspend fun verifyGeneratedStoreMigrations(
                backend: (DatabaseConfiguration) -> LifecycleStoreDelegate,
                identity: String,
            ) {
                MigrationVerifier($spec.catalog, $spec.fixtures)
                    .verify(backend, identity, generatedStoreMigrations)
            }
        """.trimIndent() + "\n"
        val manifest = buildString {
            append("ktstore-schema-manifest-v1\n")
            catalog.versions.forEach { version ->
                append("version ${version.version}\n")
                version.stores.sortedBy { it.storeName.value }.forEach { append("${it.storeName.value} ${it.manifest().replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")}\n") }
            }
        }
        val report = buildString {
            append("# Store migration operations\n\n")
            catalog.transitions.forEach { transition ->
                append("## ${transition.source.version} → ${transition.target.version}\n\n")
                transition.entries.forEach { entry ->
                    val action = when (entry) {
                        is MappedStoreMigration<*, *> -> if (entry.source.declaration.signatureForTooling() == entry.target.declaration.signatureForTooling() && entry.source.indexEncodings == entry.target.indexEncodings) "transform" else "rebuild"
                        is CreateStoreMigration -> "create"
                        is RemoveStoreMigration -> "remove (destructive)"
                    }
                    append("- $action: ${entry.source?.storeName?.value ?: "∅"} → ${entry.target?.storeName?.value ?: "∅"}\n")
                }
                append("\n")
            }
        }
        return linkedMapOf("main/GeneratedStoreMigrations.kt" to code, "test/GeneratedMigrationVerification.kt" to verification, "schemas.manifest" to manifest, "operations.md" to report.trimEnd() + "\n")
    }
    private fun StoreDeclaration.signatureForTooling(): String =
        listOf(name.value, primaryKey.name, keys.sortedBy { it.name }.joinToString { key ->
            "${key.name}:${key.nullable}:${key::class.simpleName}:" + if (key is StoreKey.CompositeKey) key.names.joinToString("+") else ""
        }).joinToString(";")

    fun historyHashes(root: File, files: List<File>): String {
        require(files.isNotEmpty()) { "Historical source and fixture inputs must be registered" }
        val base = root.canonicalFile.toPath()
        val inputs = files.flatMap { file -> if (file.isDirectory) file.walkTopDown().filter { it.isFile }.toList() else listOf(file) }
        require(inputs.isNotEmpty())
        return "ktstore-history-lock-v1\n" + inputs.map { it.canonicalFile }.distinct().sortedBy { it.relativeTo(root.canonicalFile).invariantSeparatorsPath }.joinToString("", transform = { file ->
            require(file.isFile && file.toPath().startsWith(base)) { "Historical inputs must be files beneath the project root" }
            val digest = MessageDigest.getInstance("SHA-256").digest(file.readBytes()).joinToString("") { "%02x".format(it) }
            "$digest  ${file.relativeTo(root.canonicalFile).invariantSeparatorsPath}\n"
        })
    }
    fun writeOrCheck(output: File, artifacts: Map<String, String>, check: Boolean) {
        require(output.isDirectory || !output.exists())
        if (check) {
            val temporary = Files.createTempDirectory("ktstore-generated-check").toFile()
            try {
                writeOrCheck(temporary, artifacts, false)
                artifacts.keys.forEach { name ->
                    val actual = File(output, name)
                    require(actual.isFile && actual.readBytes().contentEquals(File(temporary, name).readBytes())) { "Generated migration artifact is stale: $name" }
                }
                require(output.walkTopDown().filter { it.isFile }.map { it.relativeTo(output).invariantSeparatorsPath }.toSet() == artifacts.keys) { "Unexpected generated migration artifacts" }
            } finally { temporary.deleteRecursively() }
        } else {
            // Historical hashes cannot be silently re-baselined by generation.
            val lock = File(output, "history.lock")
            if (lock.exists()) {
                val previous = lock.readLines().drop(1).filter { it.isNotBlank() }.associate { line -> line.substringAfter("  ") to line.substringBefore("  ") }
                val next = artifacts.getValue("history.lock").lineSequence().drop(1).filter { it.isNotBlank() }.associate { line -> line.substringAfter("  ") to line.substringBefore("  ") }
                require(previous.all { (path, hash) -> next[path] == hash }) { "Historical input changed or disappeared; preserve supported history" }
            }
            val manifest = File(output, "schemas.manifest")
            if (manifest.exists()) {
                fun versions(text: String) = text.split("version ").drop(1).associate { section -> section.substringBefore('\n') to section.substringAfter('\n') }
                val previous = versions(manifest.readText())
                val next = versions(artifacts.getValue("schemas.manifest"))
                require(previous.all { (version, schema) -> next[version] == schema }) { "Historical schema changed or disappeared" }
            }
            artifacts.forEach { (name, content) -> File(output, name).apply { parentFile.mkdirs(); writeText(content) } }
        }
    }
    @JvmStatic fun main(args: Array<String>) {
        require(args.size >= 6) { "mode provider-class package specification-reference output root [historical-inputs...]" }
        val mode = args[0]
        require(mode in setOf("generate", "check", "verify"))
        val type = Class.forName(args[1])
        val spec = (runCatching { type.getField("INSTANCE").get(null) }.getOrElse { type.getDeclaredConstructor().newInstance() }) as MigrationSpecification
        val artifacts = generate(spec, args[2], args[3]) + ("history.lock" to historyHashes(File(args[5]), args.drop(6).map(::File)))
        writeOrCheck(File(args[4]), artifacts, mode != "generate")
        if (mode == "verify") {
            val temp = Files.createTempDirectory("ktstore-verification").toFile()
            try {
                runBlocking {
                    MigrationVerifier(spec.catalog, spec.fixtures).verify({ config ->
                        SqlStoreDelegate(JdbcDriver(File(temp, config.identity + ".db").absolutePath, "sqlite"), "BLOB", config)
                    }, "generated")
                }
            } finally { temp.deleteRecursively() }
        }
    }
}
