// Generated by ktstore. Edit the migration specification, then regenerate.
package example.generated

import com.latenighthack.ktstore.*

val generatedStoreMigrations: List<DatabaseMigration> = listOf(
    DatabaseMigration.configured(1, 2, example.UsersHistory.v1.declarations, example.UsersHistory.v2.declarations) {
        rebuildMappedStore(example.usersMigration.source, example.usersMigration.target, example.usersMigration.mapping)
    },
)
